services:
  toolgether-spring-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      toolgether-mysql:
        condition: service_healthy
      toolgether-redis:
        condition: service_healthy

  toolgether-mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306" # MySQL 포트를 localhost와 매핑
    environment:
      MYSQL_ROOT_PASSWORD: lldj123414
      MYSQL_DATABASE: toolgether  # 자동 생성할 DB
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql  # MySQL 데이터 유지
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10

  toolgether-redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379" # Redis 기본 포트 매핑
    volumes:
      - ./redis_data:/data # Redis 데이터 유지
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
